### ISSUE TITLE
Typo on http://www.wothke.ch/tinyrsid/index.php/webaudio-players

### ISSUE THREAD

**Issue by shlomif** [wothke/libxmp-4.3.0#5]
The page http://www.wothke.ch/tinyrsid/index.php/webaudio-players contains a typo : "just click of the below images" should be "just click on the below images". Furthermore, the contact link does not contain any contact information even with JS whitelisted.

**Comment by shlomif** [comment]
Oh, and also see - http://www.shlomifish.org/meta/FAQ/#obscure_email_addr .

**Comment by wothke** [comment]
fixed the typo and added explanation for how to find the email address

**Comment by shlomif** [comment]
Thanks!
